openapi: 3.1.0
info:
  title: AuthClient API
  version: 1.0.0
  description: API for issuing and validating JWT tokens
servers:
  - url: http://localhost:{port}
    variables:
      port:
        default: "8080"
paths:
  /validate-token:
    post:
      summary: Validate a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: The JWT token to validate
              required:
                - token
      responses:
        "200":
          description: Token is valid
        "400":
          description: Invalid token
        "500":
          description: Internal Server Error
  /issue-token:
    post:
      summary: Issue a new JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The user ID for which to issue the token
              required:
                - userId
      responses:
        "200":
          description: Token issued successfully
        "500":
          description: Internal Server Error
